const state = {
    data: {}, mapId: null, sideId: null, spawnId: null,
    mapFileData: null, mapPreviewFileData: null, sidePreviewFileData: null,
    spawnPreviewFileData: null, aimFilesData: [], resultFileData: null,
};
const $ = (s) => document.querySelector(s);
const mapsList = $("#mapsList"), sidesList = $("#sidesList"), spawnsList = $("#spawnsList"), mapStage = $("#mapStage");
function slug(v){return String(v||"").trim().toLowerCase().replace(/[^a-zа-яё0-9]+/gi,"-").replace(/^-|-$/g,"")}
function getMap(){return state.data[state.mapId]||null}
function getSide(){return getMap()?.sides?.[state.sideId]||null}
function getSpawn(){return getSide()?.spawns?.find(s=>String(s.id)===String(state.spawnId))||null}
function normalizeData(data){
    Object.entries(data||{}).forEach(([mapId,map])=>{
        if(!map||typeof map!=="object")return; map.name=map.name||mapId; map.previewImage=map.previewImage||""; map.sides=map.sides&&typeof map.sides==="object"?map.sides:{};
        Object.entries(map.sides).forEach(([sideId,side])=>{
            if(!side||typeof side!=="object") map.sides[sideId]={label:sideId,spawns:[]}; side=map.sides[sideId]; side.label=side.label||sideId; side.previewImage=side.previewImage||""; side.mapImage=side.mapImage||map.mapImage||""; side.spawns=Array.isArray(side.spawns)?side.spawns:[];
            side.spawns.forEach(spawn=>{spawn.previewImage=spawn.previewImage||spawn.preview||""; spawn.aimImages=Array.isArray(spawn.aimImages)?spawn.aimImages:(spawn.aimImage?[spawn.aimImage]:[]); spawn.aimImage=spawn.aimImage||spawn.aimImages[0]||""; spawn.resultImage=spawn.resultImage||"";});
        }); delete map.mapImage;
    }); return data||{};
}
function renderAll(){renderMaps();renderSides();renderSpawns();renderEditor()}
function thumb(src,cls="thumb"){return src?`<img class="${cls}" src="${escapeAttribute(src)}" alt="">`:`<span class="thumb thumb-empty">NO IMG</span>`}
function renderMaps(){const e=Object.entries(state.data); mapsList.innerHTML=e.length?e.map(([id,m])=>`<button class="list-item list-item_media ${id===state.mapId?"active":""}" data-map="${escapeHtml(id)}" type="button">${thumb(m.previewImage)}<div><b>${escapeHtml(m.name||id)}</b><small>${escapeHtml(id)}</small></div><span>→</span></button>`).join(""):`<div class="empty-map" style="padding:14px">Нет карт</div>`}
function renderSides(){const m=getMap(); if(!m){sidesList.innerHTML=`<div class="empty-map" style="padding:14px">Выберите карту</div>`;return} const e=Object.entries(m.sides||{}); sidesList.innerHTML=e.length?e.map(([id,s])=>`<button class="list-item list-item_media ${id===state.sideId?"active":""}" data-side="${escapeHtml(id)}" type="button">${thumb(s.previewImage||s.mapImage)}<div><b>${escapeHtml(s.label||id)}</b><small>${escapeHtml(id)} · ${(s.spawns||[]).length} точек</small></div><span>→</span></button>`).join(""):`<div class="empty-map" style="padding:14px">Нет сторон / мест</div>`}
function renderSpawns(){const s=getSide(); if(!s){spawnsList.innerHTML=`<div class="empty-map" style="padding:14px">Выберите сторону / место</div>`;return} const e=s.spawns||[]; spawnsList.innerHTML=e.length?e.map(sp=>`<button class="list-item list-item_media ${String(sp.id)===String(state.spawnId)?"active":""}" data-spawn="${escapeHtml(sp.id)}" type="button">${thumb(sp.previewImage||getAimImages(sp)[0]||sp.resultImage)}<div><b>${escapeHtml(sp.name||"Без названия")}</b><small>#${escapeHtml(sp.id)} · ${escapeHtml(sp.position||"позиция не указана")}</small></div><span>→</span></button>`).join(""):`<div class="empty-map" style="padding:14px">Нет точек</div>`}
function getAimImages(sp){return Array.isArray(sp?.aimImages)&&sp.aimImages.length?sp.aimImages:(sp?.aimImage?[sp.aimImage]:[])}
function renderEditor(){const m=getMap(),s=getSide(),sp=getSpawn(); $("#workspaceEyebrow").textContent=m?`${m.name||state.mapId}${s?" / "+(s.label||state.sideId):""}`:"ВЫБЕРИТЕ КАРТУ"; $("#workspaceTitle").textContent=sp?.name||s?.label||m?.name||"Карта"; $("#deleteCurrentBtn").style.display=(sp||s||m)?"":"none";
    $("#mapIdInput").value=state.mapId||""; $("#mapNameInput").value=m?.name||""; $("#mapPreviewPathInput").value=m?.previewImage||"";
    $("#sideIdInput").value=state.sideId||""; $("#sideLabelInput").value=s?.label||""; $("#sidePreviewPathInput").value=s?.previewImage||""; $("#mapImagePathInput").value=s?.mapImage||"";
    $("#nameInput").value=sp?.name||""; $("#spawnPreviewPathInput").value=sp?.previewImage||""; $("#xInput").value=sp?.x??""; $("#yInput").value=sp?.y??""; $("#positionInput").value=sp?.position||""; $("#throwInput").value=sp?.throw||""; $("#targetInput").value=sp?.target||""; $("#noteInput").value=sp?.note||""; $("#resultPathInput").value=sp?.resultImage||"";
    $("#mapImageName").textContent=state.mapFileData?.name||"Файл не выбран"; $("#resultImageName").textContent=state.resultFileData?.name||"Файл не выбран"; renderAimImages(); renderPreviewBoxes(); renderMapStage(); }
function renderPreviewBoxes(){const m=getMap(),s=getSide(),sp=getSpawn(); previewBox("#mapPreviewBox",state.mapPreviewFileData?.data||m?.previewImage,"Превью карты"); previewBox("#sidePreviewBox",state.sidePreviewFileData?.data||s?.previewImage||s?.mapImage,"Превью места"); previewBox("#spawnPreviewBox",state.spawnPreviewFileData?.data||sp?.previewImage||getAimImages(sp)[0]||sp?.resultImage,"Превью lineup"); previewBox("#resultPreviewBox",state.resultFileData?.data||sp?.resultImage,"Result")}
function previewBox(sel,src,label){const el=$(sel); if(!el)return; el.innerHTML=src?`<img src="${escapeAttribute(src)}" alt=""><span>${label}</span>`:`<div class="preview-empty">${label}: нет изображения</div>`}
function renderAimImages(){const sp=getSpawn(), images=state.aimFilesData.length?state.aimFilesData.map(x=>x.data):getAimImages(sp); $("#aimImagesList").innerHTML=images.length?images.map((src,i)=>`<div class="image-item"><img src="${escapeAttribute(src)}" alt=""><div><b>Aim ${i+1}</b><small>${state.aimFilesData.length?"Новый файл":"Сохранено"}</small></div><button type="button" class="icon-btn remove-aim" data-index="${i}">×</button></div>`).join(""):`<div class="empty-map">Aim-картинки не добавлены</div>`}
function renderMapStage(){const s=getSide(); if(!s){mapStage.innerHTML=`<div class="empty-map">Сначала выбери или создай место</div>`;return} const src=state.mapFileData?.data||s.mapImage; if(!src){mapStage.innerHTML=`<div class="empty-map">У этого места нет рабочей карты.<br>Точки можно редактировать без неё.</div>`;return} mapStage.innerHTML=`<img id="editorMapImage" src="${escapeAttribute(src)}" alt="">`; (s.spawns||[]).forEach(sp=>{const marker=document.createElement("button"); marker.type="button"; marker.className="marker"+(String(sp.id)===String(state.spawnId)?" active":""); marker.style.left=`${Number(sp.x)||0}%`; marker.style.top=`${Number(sp.y)||0}%`; marker.innerHTML=`${escapeHtml(sp.id)}<span>${escapeHtml(sp.name||"")}</span>`; marker.onclick=e=>{e.stopPropagation();selectSpawn(sp.id)}; mapStage.appendChild(marker)}); $("#editorMapImage").onclick=e=>{const r=e.currentTarget.getBoundingClientRect();createOrMoveSpawn(((e.clientX-r.left)/r.width)*100,((e.clientY-r.top)/r.height)*100)} }
function selectMap(id){state.mapId=id;state.sideId=null;state.spawnId=null;clearFileState();renderAll()}
function selectSide(id){state.sideId=id;state.spawnId=null;clearFileState();renderAll()}
function selectSpawn(id){state.spawnId=id;clearFileState();renderAll()}
function addMap(){const id=prompt("ID карты, например: mirage");if(!id)return;const clean=slug(id);if(!clean)return;if(state.data[clean])return alert("Такая карта уже существует.");state.data[clean]={name:prompt("Название карты:",id)||id,previewImage:"",sides:{}};state.mapId=clean;state.sideId=null;state.spawnId=null;renderAll()}
function addSide(){const m=getMap();if(!m)return alert("Сначала выбери карту.");const id=prompt("ID стороны / места:\nнапример: t, ct, mid, a-site, b-site");if(!id)return;const clean=slug(id);if(m.sides[clean])return alert("Такое место уже существует.");m.sides[clean]={label:prompt("Название:",id.toUpperCase())||id.toUpperCase(),previewImage:"",mapImage:"",spawns:[]};state.sideId=clean;state.spawnId=null;renderAll()}
function createSpawnObject(id,x=50,y=50){return{id,name:"Новый lineup",previewImage:"",x:+x.toFixed(2),y:+y.toFixed(2),position:"",throw:"Jumpthrow",target:"",aimImages:[],aimImage:"",resultImage:"",note:""}}
function addSpawn(){const s=getSide();if(!s)return alert("Сначала выбери сторону / место.");const id=nextSpawnId(s);s.spawns.push(createSpawnObject(id));state.spawnId=id;clearFileState();renderAll()}
function nextSpawnId(s){return(s.spawns||[]).reduce((m,sp)=>Math.max(m,Number(sp.id)||0),0)+1}
function createOrMoveSpawn(x,y){const s=getSide();if(!s)return alert("Сначала создай/выбери место.");let sp=getSpawn();if(!sp){const id=nextSpawnId(s);sp=createSpawnObject(id,x,y);s.spawns.push(sp);state.spawnId=id}else{sp.x=+x.toFixed(2);sp.y=+y.toFixed(2)}renderAll()}
function saveForm(){const m=getMap();if(!m)return alert("Нет выбранной карты.");const newMapId=slug($("#mapIdInput").value||state.mapId);if(!newMapId)return alert("Укажи ID карты.");if(newMapId!==state.mapId&&state.data[newMapId])return alert("Этот ID карты уже занят.");if(newMapId!==state.mapId){state.data[newMapId]=m;delete state.data[state.mapId];state.mapId=newMapId}m.name=$("#mapNameInput").value.trim()||state.mapId;m.previewImage=state.mapPreviewFileData?.data||$("#mapPreviewPathInput").value.trim();const s=getSide();if(!s){clearFileState();renderAll();return alert("Карта сохранена.")};const newSideId=slug($("#sideIdInput").value||state.sideId);if(!newSideId)return alert("Укажи ID места / стороны.");if(newSideId!==state.sideId&&m.sides[newSideId])return alert("Этот ID места уже занят.");if(newSideId!==state.sideId){m.sides[newSideId]=s;delete m.sides[state.sideId];state.sideId=newSideId}s.label=$("#sideLabelInput").value.trim()||state.sideId;s.previewImage=state.sidePreviewFileData?.data||$("#sidePreviewPathInput").value.trim();s.mapImage=state.mapFileData?.data||$("#mapImagePathInput").value.trim();const sp=getSpawn();if(sp){sp.name=$("#nameInput").value.trim()||"Новый lineup";if($("#xInput").value!=="")sp.x=Number($("#xInput").value);if($("#yInput").value!=="")sp.y=Number($("#yInput").value);sp.previewImage=state.spawnPreviewFileData?.data||$("#spawnPreviewPathInput").value.trim();sp.position=$("#positionInput").value.trim();sp.throw=$("#throwInput").value.trim();sp.target=$("#targetInput").value.trim();sp.note=$("#noteInput").value.trim();if(state.aimFilesData.length)sp.aimImages=state.aimFilesData.map(x=>x.data);sp.aimImages=Array.isArray(sp.aimImages)?sp.aimImages:[];sp.aimImage=sp.aimImages[0]||"";sp.resultImage=state.resultFileData?.data||$("#resultPathInput").value.trim()}clearFileState();renderAll();alert("Сохранено. Теперь нажми «Скачать data.js».")}
function deleteCurrent(){const sp=getSpawn(),s=getSide(),m=getMap();if(sp&&s){if(!confirm("Удалить этот lineup?"))return;s.spawns=s.spawns.filter(x=>String(x.id)!==String(state.spawnId));state.spawnId=null}else if(s&&m){if(!confirm("Удалить это место / сторону?"))return;delete m.sides[state.sideId];state.sideId=null;state.spawnId=null}else if(m){if(!confirm("Удалить карту целиком?"))return;delete state.data[state.mapId];state.mapId=null;state.sideId=null;state.spawnId=null}renderAll()}
function addAimPath(){const input=$("#aimPathInput"),path=input.value.trim(),sp=getSpawn();if(!path)return;if(!sp)return alert("Сначала выбери или создай lineup.");sp.aimImages=Array.isArray(sp.aimImages)?sp.aimImages:[];sp.aimImages.push(path);sp.aimImage=sp.aimImages[0]||"";input.value="";renderAimImages();renderPreviewBoxes()}
function removeAim(index){const sp=getSpawn();if(!sp)return;sp.aimImages=Array.isArray(sp.aimImages)?sp.aimImages:[];sp.aimImages.splice(index,1);sp.aimImage=sp.aimImages[0]||"";renderAimImages();renderPreviewBoxes()}
function readFile(file,setter,rerender=true){if(!file)return;const r=new FileReader();r.onload=()=>{setter({data:r.result,name:file.name});if(rerender)renderEditor()};r.readAsDataURL(file)}
function readMultipleFiles(files){const selected=Array.from(files||[]);if(!selected.length)return;Promise.all(selected.map(file=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve({data:r.result,name:file.name});r.readAsDataURL(file)}))).then(items=>{state.aimFilesData=items;renderAimImages();renderPreviewBoxes()})}
function clearFileState(){state.mapFileData=null;state.mapPreviewFileData=null;state.sidePreviewFileData=null;state.spawnPreviewFileData=null;state.aimFilesData=[];state.resultFileData=null}
function dataToJs(){return`/* Generated by CS2 Insta Smokes Admin */\nconst smokeData = ${JSON.stringify(state.data,null,4)};\n`}
function download(filename,content){const blob=new Blob([content],{type:"text/javascript;charset=utf-8"}),link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function escapeHtml(v){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function escapeAttribute(v){return String(v??"").replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
mapsList.onclick=e=>{const b=e.target.closest("[data-map]");if(b)selectMap(b.dataset.map)};sidesList.onclick=e=>{const b=e.target.closest("[data-side]");if(b)selectSide(b.dataset.side)};spawnsList.onclick=e=>{const b=e.target.closest("[data-spawn]");if(b)selectSpawn(b.dataset.spawn)};$("#aimImagesList").onclick=e=>{const b=e.target.closest(".remove-aim");if(b)removeAim(Number(b.dataset.index))};
$("#addMapBtn").onclick=addMap;$("#addSideBtn").onclick=addSide;$("#addSpawnBtn").onclick=addSpawn;$("#saveBtn").onclick=saveForm;$("#deleteCurrentBtn").onclick=deleteCurrent;$("#addAimPathBtn").onclick=addAimPath;$("#exportBtn").onclick=()=>download("data.js",dataToJs());$("#importBtn").onclick=()=>$("#importFile").click();
$("#importFile").onchange=async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();let imported=null;const match=text.match(/const\s+smokeData\s*=\s*([\s\S]*?);\s*$/);if(match){try{imported=Function(`"use strict"; return (${match[1]})`)()}catch(err){console.error(err)}}if(!imported){try{imported=JSON.parse(text)}catch(err){console.error(err)}}if(!imported||typeof imported!=="object")return alert("Не удалось прочитать data.js.");state.data=normalizeData(imported);state.mapId=null;state.sideId=null;state.spawnId=null;clearFileState();renderAll();alert("data.js импортирован.")};
$("#mapImageInput").onchange=e=>readFile(e.target.files[0],v=>state.mapFileData=v);$("#mapPreviewInput").onchange=e=>readFile(e.target.files[0],v=>state.mapPreviewFileData=v);$("#sidePreviewInput").onchange=e=>readFile(e.target.files[0],v=>state.sidePreviewFileData=v);$("#spawnPreviewInput").onchange=e=>readFile(e.target.files[0],v=>state.spawnPreviewFileData=v);$("#aimImageInput").onchange=e=>readMultipleFiles(e.target.files);$("#resultImageInput").onchange=e=>readFile(e.target.files[0],v=>state.resultFileData=v);
state.data={};renderAll();
